In [1]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)

__Домашняя работа 3.__

__Задание 1.__ Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей  

$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}.$

detA = (-1 -x)*(6-x) +12 = -6 + x - 6x + x^2 + 12 = x^2 - 5x + 6

D = 25 - 24 = 1    
x = (2,3) - Собственные значения

In [3]:
a = np.array([[-1, -6], [2, 6]])
w, v = np.linalg.eig(a)
 
print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v} (по столбцам)')

Матрица A:
[[-1 -6]
 [ 2  6]]
Собственные значения:
[2. 3.]
Собственные векторы:
[[-0.89  0.83]
 [ 0.45 -0.55]] (по столбцам)


In [4]:
s = np.array([[-0.89, 0.45]])
t = np.array([[0.83, -0.55]])
d = v[0]
print(a.dot(s.T).T)
print(a.dot(t.T).T)

[[-1.81  0.92]]
[[ 2.47 -1.64]]


In [5]:
print(s*2)
print(t*3)

[[-1.78  0.9 ]]
[[ 2.49 -1.65]]


__Задание 2.__ Дан оператор поворота на 180 градусов, задаваемый матрицей 

$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$

Показать, что __любой__ вектор является для него собственным.

detA = (-1 -x)^2 = x^2 +2x +1     
D = 0   
x = -1 (Собственное значение)

$\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}
\begin{pmatrix}
s\\ 
t
\end{pmatrix}=
\begin{pmatrix}
-s\\ 
-t
\end{pmatrix}
$

Для любого вектора умножение на собственное значение оператора А будет давать тот же результат, что и применение самого оператора А. То есть любой вектор будет собственным для оператора А

__Задание 3.__ Пусть линейный оператор задан матрицей

$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$

Установить, является ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.

$\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}
\begin{pmatrix}
1\\ 
1
\end{pmatrix}=
\begin{pmatrix}
1 + 1\\ 
-1 + 3
\end{pmatrix}=
\begin{pmatrix}
2\\ 
2
\end{pmatrix}=
2*
\begin{pmatrix}
1\\ 
1
\end{pmatrix}
$

Ответ: Да, является.

**Задание 4.** Пусть линейный оператор задан матрицей

$A=\begin{pmatrix} 0 & 3 & 0\\ 3 & 0 & 0\\ 0 & 0 & 3 \end{pmatrix}.$

Установить, является ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.

$\begin{pmatrix}
0 & 3 & 0 \\ 
3 & 0 & 0 \\
0 & 0 & 3
\end{pmatrix}
\begin{pmatrix}
3\\ 
-3\\
-4
\end{pmatrix}=
\begin{pmatrix}
-9\\ 
9\\
-12
\end{pmatrix}
$

Нет, не является, так как невозможно подобрать такую константу, при умножении на которую знак менялся бы не у всех ненулевых элементов вектора