In [12]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)

__Домашняя работа 5.__

__Задание 1.__ Найти с помощью NumPy SVD для матрицы

$\begin{pmatrix}
1 & 2 & 0\\ 
0 & 0 & 5\\ 
3 & -4 & 2\\ 
1 & 6 & 5\\ 
0 & 1 & 0
\end{pmatrix}.$

In [13]:
A = np.matrix([[1,2,0],[0,0,5],[3,-4,2],[1,6,5],[0,1,0]])
A

matrix([[ 1,  2,  0],
        [ 0,  0,  5],
        [ 3, -4,  2],
        [ 1,  6,  5],
        [ 0,  1,  0]])

In [14]:
U, s, W = np.linalg.svd(A)
# Транспонируем матрицу W
V = W.T
# s - список диагональных элементов, его нужно привести к виду диагональной матрицы для наглядности
D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s

In [18]:
# Проверка
print(np.dot(np.dot(U, D), V.T))

[[ 1.  2.  0.]
 [ 0. -0.  5.]
 [ 3. -4.  2.]
 [ 1.  6.  5.]
 [-0.  1.  0.]]


__Задание 2.__ Для матрицы из предыдущего задания найти:

    а) евклидову норму;
    
    б) норму Фробениуса.

In [21]:
print(f'Евклидова норма:{np.linalg.norm(A, ord=2)}\nНорма Фробениуса:{np.linalg.norm(A, ord=None)}')

Евклидова норма:8.824868854820444
Норма Фробениуса:11.045361017187261
