In [1]:
import numpy as np
import random
import torch

Домашнее задание

1. Создайте случайный FloatTensor размера 3x4x5

In [2]:
a = torch.randn(3, 4, 5)

In [3]:
a

tensor([[[-0.3972,  0.2084, -0.4110, -1.6633,  0.3450],
         [-1.9700, -1.3304,  0.5269,  1.4126, -1.2725],
         [ 0.5579, -0.6015, -0.5431, -0.3205,  0.1690],
         [-0.7900, -1.1936,  0.4959, -0.4659, -1.2089]],

        [[ 1.2526,  0.6571, -0.7641, -0.2699,  0.1572],
         [ 0.5564,  0.5424, -0.4787,  1.3926,  1.2320],
         [-1.5554,  0.6334,  1.1038,  0.4130,  1.9582],
         [ 0.4966,  0.4243, -0.2217, -0.2412,  0.1341]],

        [[-0.1000,  0.6316,  0.9084, -1.2693,  0.8770],
         [ 0.0348, -0.6375,  0.5921,  0.7542, -0.9532],
         [ 2.0145,  0.0957,  1.4377, -0.7977,  1.0249],
         [ 0.6774, -0.3416,  0.6287, -0.2933, -0.1397]]])

2. Выведите его форму

In [4]:
a.shape

torch.Size([3, 4, 5])

3. Приведите его к форме 6х10

In [5]:
a = a.reshape(6, 10)

In [6]:
a.shape

torch.Size([6, 10])

4. Создайте случайный intTensor размера 10

In [7]:
b = torch.randint(10, size=(10,1))
b

tensor([[0],
        [6],
        [1],
        [9],
        [3],
        [2],
        [0],
        [5],
        [8],
        [9]])

5. Умножьте созданный FloatTensor на созданный IntTensor поэлементно

In [8]:
#выполнить задание напрямую невозможно, матрицы не подходят. Транспонируем тензор b

In [9]:
b = b.T

In [10]:
b.shape

torch.Size([1, 10])

In [11]:
c = a*b

In [12]:
c

tensor([[ -0.0000,   1.2504,  -0.4110, -14.9695,   1.0350,  -3.9400,  -0.0000,
           2.6346,  11.3006, -11.4524],
        [  0.0000,  -3.6088,  -0.5431,  -2.8842,   0.5069,  -1.5800,  -0.0000,
           2.4794,  -3.7276, -10.8805],
        [  0.0000,   3.9426,  -0.7641,  -2.4292,   0.4717,   1.1128,   0.0000,
          -2.3934,  11.1405,  11.0878],
        [ -0.0000,   3.8006,   1.1038,   3.7170,   5.8746,   0.9931,   0.0000,
          -1.1083,  -1.9295,   1.2065],
        [ -0.0000,   3.7894,   0.9084, -11.4235,   2.6311,   0.0697,  -0.0000,
           2.9607,   6.0339,  -8.5788],
        [  0.0000,   0.5743,   1.4377,  -7.1790,   3.0746,   1.3548,  -0.0000,
           3.1434,  -2.3462,  -1.2569]])

6. Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
Подсказка: .dot может не подойти

In [13]:
d = c*c # не понял задания( 

In [14]:
d.shape

torch.Size([6, 10])

7. Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

In [52]:
X = torch.tensor([1., 0.5, 2.], requires_grad = True)
X.shape

torch.Size([3])

In [53]:
y = X[0]**3 + X[1] - 75*X[2] 

In [54]:
y.shape

torch.Size([])

In [55]:
y.backward() # сюда надо что-то передавать ли нет? На уроке был пример с одной переменной и там передавалось. Но если написать y.backward(X) то ошибка. 

In [56]:
print(X.grad) # в общем это задание тоже не понял. Искал в интернете, но везде в примерах даются производные с одной переменной. Как объединять несколько разных непонятно.

tensor([  3.,   1., -75.])


8. Создайте единичный тензор размера 5x6

In [19]:
x = torch.ones(5, 6)
x

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

9. Переведите его в формат numpy

In [42]:
x = x.numpy()